import { Icon } from '@iconify/react'

export default function NotificationHistory({ history, search, onSearch, onSelect }) {
  const filtered = history.filter((item) => item.title.toLowerCase().includes(search.toLowerCase()) || item.body.toLowerCase().includes(search.toLowerCase()) || item.audience.toLowerCase().includes(search.toLowerCase()))
  return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-xs">
    <div className="flex items-center justify-between gap-2"><h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Icon icon="lucide:history" width="16" className="text-primary" />Notifikasi Terkini</h3><span className="text-xs text-slate-400">{history.length} terkirim</span></div>
    <div className="relative mt-3"><Icon icon="lucide:search" width="14" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Cari riwayat..." className="w-full rounded-lg border border-slate-200 bg-slate-50 py-1.5 pl-8 pr-3 text-xs focus:border-secondary focus:outline-none focus:ring-1 focus:ring-secondary" /></div>
    <div className="mt-3 max-h-80 divide-y divide-slate-100 overflow-y-auto">{filtered.length === 0 ? <div className="py-8 text-center text-xs text-slate-400">Tidak ada notifikasi.</div> : filtered.map((item) => <div key={item.id} onClick={() => onSelect(item)} className="cursor-pointer rounded-lg px-2 py-3 transition hover:bg-slate-50"><div className="flex items-start justify-between gap-2"><p className="truncate text-xs font-bold text-slate-800">{item.title}</p><span className="shrink-0 text-[10px] text-slate-400">{item.terkirimAt}</span></div><p className="mt-1 line-clamp-1 text-xs text-slate-500">{item.body}</p><div className="mt-2 flex items-center justify-between text-[11px]"><span className="text-slate-400">Kepada: <span className="font-medium text-slate-600">{item.audience}</span></span><span className="flex items-center gap-1 font-semibold text-emerald-600"><Icon icon="lucide:check-check" width="12" />{item.recipientCount} pengguna</span></div></div>)}</div>
  </div>
}
